version: '3.8'
services:
  php-apache-environment:
    container_name: redlockphp
    build:
      context: ./php
      dockerfile: DockerFile

    depends_on:
      - hades

    volumes:
    - ./php/src:/var/www/html

    ports:
    - 7077:80


  hades:
    container_name: hades
    image: mysql
    restart: always
    environment:       
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: poseidon
          MYSQL_USER: MYSQL_USER
          MYSQL_PASSWORD: MYSQL_PASSWORD

    ports:
      - "9906:3306"


  pmhades:
    image: phpmyadmin/phpmyadmin
    ports: 
      - '8080:80'
    restart: always
    environment:
      - PMA_HOST: hades
    depends_on:
      - hades
